# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35709f927510253322791830a548627aadc143560a630df96c60573c44d3e599bc5649d94d740750c6d80e851b19d558a2b0c3454f7d72def62de2727487f44c

test:
  secret_key_base: c6c86a59c571ec2a9732ff9d9b53a021567ef15624d9a2de86dbf8dd086585aaf60e78f27a840f367a5611316f9fed92f22aec4b2a7a3bbd2e67a51459cdab45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
